/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mastermind_sf_lb;

/**
 *
 * @author leaburriat
 */
public class fenetreDeJeu extends javax.swing.JFrame {

    /**
     * Creates new form fenetreDeJeu
     */
    public fenetreDeJeu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panneau_grille = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jButton36 = new javax.swing.JButton();
        jButton37 = new javax.swing.JButton();
        jButton38 = new javax.swing.JButton();
        jButton39 = new javax.swing.JButton();
        jButton40 = new javax.swing.JButton();
        jButton41 = new javax.swing.JButton();
        jButton42 = new javax.swing.JButton();
        jButton43 = new javax.swing.JButton();
        jButton44 = new javax.swing.JButton();
        jButton45 = new javax.swing.JButton();
        jButton46 = new javax.swing.JButton();
        jButton47 = new javax.swing.JButton();
        jButton48 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        panneau_message = new javax.swing.JPanel();
        lbl_message = new javax.swing.JLabel();
        panneau_couleurs = new javax.swing.JPanel();
        lbl_palette_couleurs = new javax.swing.JLabel();
        lbl_palette_couleurs1 = new javax.swing.JLabel();
        couleur1 = new javax.swing.JButton();
        couleur4 = new javax.swing.JButton();
        couleur2 = new javax.swing.JButton();
        couleur5 = new javax.swing.JButton();
        couleur3 = new javax.swing.JButton();
        couleur6 = new javax.swing.JButton();
        panneau_infos = new javax.swing.JPanel();
        lbl_infos_partie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panneau_grille.setBackground(new java.awt.Color(204, 204, 204));
        panneau_grille.setLayout(new java.awt.GridLayout(12, 4));

        jButton1.setText("jButton1");
        panneau_grille.add(jButton1);

        jButton2.setText("jButton2");
        panneau_grille.add(jButton2);

        jButton3.setText("jButton3");
        panneau_grille.add(jButton3);

        jButton4.setText("jButton4");
        panneau_grille.add(jButton4);

        jButton5.setText("jButton4");
        panneau_grille.add(jButton5);

        jButton6.setText("jButton4");
        panneau_grille.add(jButton6);

        jButton7.setText("jButton4");
        panneau_grille.add(jButton7);

        jButton8.setText("jButton4");
        panneau_grille.add(jButton8);

        jButton9.setText("jButton4");
        panneau_grille.add(jButton9);

        jButton10.setText("jButton4");
        panneau_grille.add(jButton10);

        jButton11.setText("jButton4");
        panneau_grille.add(jButton11);

        jButton12.setText("jButton4");
        panneau_grille.add(jButton12);

        jButton13.setText("jButton4");
        panneau_grille.add(jButton13);

        jButton14.setText("jButton4");
        panneau_grille.add(jButton14);

        jButton15.setText("jButton4");
        panneau_grille.add(jButton15);

        jButton16.setText("jButton4");
        panneau_grille.add(jButton16);

        jButton17.setText("jButton4");
        panneau_grille.add(jButton17);

        jButton18.setText("jButton4");
        panneau_grille.add(jButton18);

        jButton19.setText("jButton4");
        panneau_grille.add(jButton19);

        jButton20.setText("jButton4");
        panneau_grille.add(jButton20);

        jButton21.setText("jButton4");
        panneau_grille.add(jButton21);

        jButton22.setText("jButton4");
        panneau_grille.add(jButton22);

        jButton23.setText("jButton4");
        panneau_grille.add(jButton23);

        jButton24.setText("jButton4");
        panneau_grille.add(jButton24);

        jButton25.setText("jButton4");
        panneau_grille.add(jButton25);

        jButton26.setText("jButton4");
        panneau_grille.add(jButton26);

        jButton27.setText("jButton4");
        panneau_grille.add(jButton27);

        jButton28.setText("jButton4");
        panneau_grille.add(jButton28);

        jButton29.setText("jButton4");
        panneau_grille.add(jButton29);

        jButton30.setText("jButton4");
        panneau_grille.add(jButton30);

        jButton31.setText("jButton4");
        panneau_grille.add(jButton31);

        jButton32.setText("jButton4");
        panneau_grille.add(jButton32);

        jButton33.setText("jButton4");
        panneau_grille.add(jButton33);

        jButton34.setText("jButton4");
        panneau_grille.add(jButton34);

        jButton35.setText("jButton4");
        panneau_grille.add(jButton35);

        jButton36.setText("jButton4");
        panneau_grille.add(jButton36);

        jButton37.setText("jButton4");
        panneau_grille.add(jButton37);

        jButton38.setText("jButton4");
        panneau_grille.add(jButton38);

        jButton39.setText("jButton4");
        panneau_grille.add(jButton39);

        jButton40.setText("jButton4");
        panneau_grille.add(jButton40);

        jButton41.setText("jButton4");
        panneau_grille.add(jButton41);

        jButton42.setText("jButton4");
        panneau_grille.add(jButton42);

        jButton43.setText("jButton4");
        panneau_grille.add(jButton43);

        jButton44.setText("jButton4");
        panneau_grille.add(jButton44);

        jButton45.setText("jButton4");
        panneau_grille.add(jButton45);

        jButton46.setText("jButton4");
        panneau_grille.add(jButton46);

        jButton47.setText("jButton4");
        panneau_grille.add(jButton47);

        jButton48.setText("jButton4");
        panneau_grille.add(jButton48);

        getContentPane().add(panneau_grille, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 550, 520));

        jLabel1.setFont(new java.awt.Font("American Typewriter", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("MasterMind");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 550, 80));

        panneau_message.setBackground(new java.awt.Color(153, 153, 153));

        lbl_message.setText("Messages :");

        javax.swing.GroupLayout panneau_messageLayout = new javax.swing.GroupLayout(panneau_message);
        panneau_message.setLayout(panneau_messageLayout);
        panneau_messageLayout.setHorizontalGroup(
            panneau_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_messageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_message)
                .addContainerGap(325, Short.MAX_VALUE))
        );
        panneau_messageLayout.setVerticalGroup(
            panneau_messageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_messageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_message)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(panneau_message, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 400, 80));

        panneau_couleurs.setBackground(new java.awt.Color(153, 153, 153));
        panneau_couleurs.setLayout(new java.awt.GridLayout(4, 3));

        lbl_palette_couleurs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_palette_couleurs.setText("Palette de couleurs :");
        panneau_couleurs.add(lbl_palette_couleurs);
        panneau_couleurs.add(lbl_palette_couleurs1);

        couleur1.setText("Rouge");
        couleur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couleur1ActionPerformed(evt);
            }
        });
        panneau_couleurs.add(couleur1);

        couleur4.setText("Vert");
        panneau_couleurs.add(couleur4);

        couleur2.setText("Jaune");
        panneau_couleurs.add(couleur2);

        couleur5.setText("Bleu");
        panneau_couleurs.add(couleur5);

        couleur3.setText("Orange");
        couleur3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couleur3ActionPerformed(evt);
            }
        });
        panneau_couleurs.add(couleur3);

        couleur6.setText("Magenta");
        couleur6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                couleur6ActionPerformed(evt);
            }
        });
        panneau_couleurs.add(couleur6);

        getContentPane().add(panneau_couleurs, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 400, 280));

        panneau_infos.setBackground(new java.awt.Color(153, 153, 153));

        lbl_infos_partie.setText("Infos partie :");

        javax.swing.GroupLayout panneau_infosLayout = new javax.swing.GroupLayout(panneau_infos);
        panneau_infos.setLayout(panneau_infosLayout);
        panneau_infosLayout.setHorizontalGroup(
            panneau_infosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_infosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_infos_partie)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        panneau_infosLayout.setVerticalGroup(
            panneau_infosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panneau_infosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_infos_partie)
                .addContainerGap(198, Short.MAX_VALUE))
        );

        getContentPane().add(panneau_infos, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 120, 400, 220));

        setBounds(0, 0, 1030, 693);
    }// </editor-fold>//GEN-END:initComponents

    private void couleur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couleur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_couleur1ActionPerformed

    private void couleur3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couleur3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_couleur3ActionPerformed

    private void couleur6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_couleur6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_couleur6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fenetreDeJeu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fenetreDeJeu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton couleur1;
    private javax.swing.JButton couleur2;
    private javax.swing.JButton couleur3;
    private javax.swing.JButton couleur4;
    private javax.swing.JButton couleur5;
    private javax.swing.JButton couleur6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton36;
    private javax.swing.JButton jButton37;
    private javax.swing.JButton jButton38;
    private javax.swing.JButton jButton39;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton40;
    private javax.swing.JButton jButton41;
    private javax.swing.JButton jButton42;
    private javax.swing.JButton jButton43;
    private javax.swing.JButton jButton44;
    private javax.swing.JButton jButton45;
    private javax.swing.JButton jButton46;
    private javax.swing.JButton jButton47;
    private javax.swing.JButton jButton48;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbl_infos_partie;
    private javax.swing.JLabel lbl_message;
    private javax.swing.JLabel lbl_palette_couleurs;
    private javax.swing.JLabel lbl_palette_couleurs1;
    private javax.swing.JPanel panneau_couleurs;
    private javax.swing.JPanel panneau_grille;
    private javax.swing.JPanel panneau_infos;
    private javax.swing.JPanel panneau_message;
    // End of variables declaration//GEN-END:variables
}
